apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: lgtm
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.9
    helm:
      valueFiles:
        - $values/lgtm-gitops/apps/grafana/values.yml
  - repoURL: 'https://github.com/alihajjhassan98/getting-started.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  clusterResourceWhitelist:
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'