apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: lgtm
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1
    helm:
      valueFiles:
        - ../apps/loki/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true