apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: lgtm
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: 1.23.1
    helm:
      valueFiles:
        - $values/lgtm-gitops/apps/tempo/values.yml
  - repoURL: 'https://github.com/alihajjhassan98/getting-started.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true