loki:
  serviceAccount:
    create: true
    annotations:
      iam.gke.io/gcp-service-account: loki-mimir-sa@dotted-vortex-462612-a7.iam.gserviceaccount.com

  gcs:
    bucket_name: loki_bucket-1
    serviceAccount: /etc/gcp/gcp-sa.json

  storage:
    type: gcs
    bucketNames:
      chunks: loki_bucket-1
      ruler: loki_bucket-1

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache

  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: index_
          period: 24h

  ingester:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClassName: standard

  containerSecurityContext:
    runAsUser: 10001
    runAsGroup: 10001

  securityContext:
    fsGroup: 10001

  extraVolumes:
    - name: gcp-sa
      secret:
        secretName: gcp-sa-secret

  extraVolumeMounts:
    - name: gcp-sa
      mountPath: /etc/gcp
      readOnly: true