loki:
  gcs:
    bucket_name: loki_bucket-1
    serviceAccount: /etc/gcp/gcp-sa.json

  extraVolumes:
    - name: gcp-sa
      secret:
        secretName: gcp-sa-secret

  extraVolumeMounts:
    - name: gcp-sa
      mountPath: /etc/gcp
      readOnly: true

  storage:
    bucketNames:
      chunks: loki_bucket-1
      ruler: loki_bucket-1
    type: gcs

  storage_config:
    boltdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/cache

  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: index_
          period: 24h

  memcached:
    chunk_cache:
      enabled: true
    results_cache:
      enabled: true

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard

  containerSecurityContext:
    runAsUser: 10001
    runAsGroup: 10001

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: loki-mimir-sa@dotted-vortex-462612-a7.iam.gserviceaccount.com