  # -- Base config file for Grafana Mimir and Grafana Enterprise Metrics. Contains Helm templates that are evaulated at install/upgrade.
  # To modify the resulting configuration, either copy and alter 'mimir.config' as a whole or use the 'mimir.structuredConfig' to add and modify certain YAML elements.
  gcs:
    bucket_name: mimir_bucket-1
    serviceAccount: /etc/gcp/gcp-sa.json

  extraVolumes:
    - name: gcp-sa
      secret:
        secretName: gcp-sa-secret

  extraVolumeMounts:
    - name: gcp-sa
      mountPath: /etc/gcp
      readOnly: true

  structuredConfig:
    usage_stats:
      enabled: false
    limits:
      max_global_series_per_user: 10000000
      # enables exemplar storage
      max_global_exemplars_per_user: 10000000
    common:
      storage:
        backend: gcs
    alertmanager_storage:
      gcs:
        bucket_name: mimir_bucket-1
    ruler_storage:
      gcs:
        bucket_name: mimir_bucket-1
    blocks_storage:
      backend: gcs
      gcs:
        bucket_name:  mimir_bucket-1

  ingester:
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: standard

  serviceAccount:
      create: true
      annotations:
          iam.gke.io/gcp-service-account: loki-mimir-sa@dotted-vortex-462612-a7.iam.gserviceaccount.com